import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/navbar/Navbar";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Collaboration Hub",
  description: "Generated by Fahmida",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
        suppressHydrationWarning>
   <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
         
       <Providers>
          <Navbar/>
         {children}
       </Providers>
    
        </body>
    </html>
  );
}
